name: Bug report
description: Report a crash, incorrect behavior, or regression.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug. Please include as much detail as possible.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened? What did you expect?
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: Minimal steps, including drawlist/event inputs if relevant.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, terminal emulator, compiler, CMake preset, etc.
      placeholder: |
        OS:
        Terminal:
        Compiler:
        Preset:
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / output
      description: Paste relevant logs, assertions, sanitizer output, etc.
    validations:
      required: false
